name: Semantic Release
on:
  push:
    branches: [x]

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: m19c/action-lerna@1.0.0
        with:
          args: bootstrap
      - run: ls -la
