name: Semantic Release
on:
  push:
    branches: [master]

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-18.04
    env:
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - uses: m19c/action-lerna@1.0.0
        with:
          args: bootstrap
      - run: |
          echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          echo "registry=https://npm.pkg.github.com/" >> ~/.npmrc
          cat ~/.npmrc
          npm whoami
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run semantic-release
