name: Semantic Release
on:
  push:
    branches: [master]

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: wetendorff
      - run: npm ci
      - uses: m19c/action-lerna@1.0.0
        with:
          args: bootstrap
      - run: echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "@wetendorff:registry=https://npm.pkg.github.com/" >> ~/.npmrc
      - run: cat ~/.npmrc
      - run: npm whoami
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run semantic-release
